### ISSUE TITLE
installation failed using brew on MacOS platform

### ISSUE THREAD

**Issue by ken5scal** [DataDog/threatest#23]
**What is not working?**
Installation using homebrew failed. Not sure whether it's due to the brew or datadog/threatest

**What OS are you using?**
Mac OS X 13.4.1 (c) (22F770820d) (Apple M1 Pro)

**What version of threatest are you using?**
NA

**Code to reproduce the issue**
```
% brew tap datadog/threatest https://github.com/datadog/threatest
% brew install datadog/threatest/threatest
```

**Full output?**

```
% brew install datadog/threatest/threatest
Error: invalid attribute for formula 'datadog/threatest/threatest': url ("https://github.com/DataDog/threatest/releases/download/v1.2.2/darwin: Darwin threatest_ linux: LinuxDarwin_ windows: Windowsarm64.tar.gz")
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:313:in `validate_attributes!'
/opt/homebrew/Library/Homebrew/formula.rb:243:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:484:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:484:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:644:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:761:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:649:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:645:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:645:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:318:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by christophetd** [comment]
Thanks for reporting! Looking into this.

**Comment by christophetd** [comment]
Closing as resolved, but feel free to reopen if you encounter any issue!

**Comment by ken5scal** [comment]
@christophetd Thanks, I have successfully installed it :)
